<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE agenda [
    <!ELEMENT agenda (contact)>
        <!ELEMENT contact (name,surname,address,phone_numbers)>
            <!ELEMENT name (#PCDATA)>
            <!ELEMENT surname (#PCDATA)>
            <!ELEMENT address (street,number,floor,zip_code,city)>
                <!ELEMENT street (#PCDATA)>
                <!ELEMENT number (#PCDATA)>
                <!ELEMENT zip_code (#PCDATA)>
                <!ELEMENT city (#PCDATA)>
            <!ELEMENT phone_numbers (home,mobile,work)>
                <!ELEMENT home (#PCDATA)>
                <!ELEMENT mobile (#PCDATA)>
                <!ELEMENT work (#PCDATA)>
]>

<agenda>
    <contact>
        <name>John</name>
        <surname>Doe</surname>
        <address>
            <street>123 Main Street</street>
            <number>48</number>
            <floor>7</floor>
            <zip_code>10001</zip_code>
            <city>New York</city>
        </address>
        <phone_numbers>
            <home>555-123-4567</home>
            <mobile>555-987-6543</mobile>
            <work>555-789-0123</work>
        </phone_numbers>
    </contact>
</agenda>
